language: python
python:
 - "3.6"
install:
 - git clone https://github.com/woctezuma/hidden-gems-data.git
 - mv hidden-gems-data/*.txt .
 - pip install codecov
 - pip install -r requirements.txt
script:
 - coverage run tests.py
after_success:
 - codecov
